# This is a generated file. Not intended for manual editing.
services:
  voterapp.api:
    build:
      context: "C:\\Users\\zupqa\\Stuff\\Repo\\VoterApp\\VoterApp"
      dockerfile: "VoterApp.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/VoterApp.Api.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\zupqa\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\zupqa\\.nuget\\packages"
    image: "voterapp.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\zupqa\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "C:\\Users\\zupqa\\Stuff\\Repo\\VoterApp\\VoterApp\\VoterApp.Api:/app:rw"
    - "C:\\Users\\zupqa\\Stuff\\Repo\\VoterApp\\VoterApp:/src:rw"
    working_dir: "/app"
